name: "My Cloud9"
version: "0.2.0b"
slug: "mycloud9"
description: "My Cloud 9"
url: https://github.com/GiudiciMattia/MyHomeAssistantRepo/tree/main/3-NewIDE
init: false
ingress: true
ingress_stream: true
panel_icon: mdi:cloud-upload
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
auth_api: true
startup: before
ports:
  80/tcp: 80
ports_description:
  80/tcp: Web interface (Not required for Ingress)  
map:
  - config:rw
  - ssl  
