name: "My Cloud9"
version: "0.1.6"
slug: "mycloud9"
description: "My Cloud 9"
url: https://github.com/GiudiciMattia/MyHomeAssistantRepo/tree/main/3-NewIDE
init: false
ingress: true
ingress_stream: true
panel_icon: mdi:cloud-upload
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  8321/tcp: 8321
map:
  - config:rw
  - ssl  
