name: "My Cloud9"
description: "My Cloud9"
version: "0.1.2"
slug: "mycloud9"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: https://github.com/GiudiciMattia/MyHomeAssistantRepo/tree/main/3-NewIDE
startup: before
ports:
  8321/tcp: 8321
map:
  - config:rw
  - ssl  
