name: "My Cloud9"
version: "0.1.3"
slug: "mycloud9"
description: "My Cloud9"
url: https://github.com/GiudiciMattia/MyHomeAssistantRepo/tree/main/3-NewIDE
init: false
ingress: true
ingress_stream: true
panel_icon: mdi:cloud-upload
homeassistant: 0.92.0b2
homeassistant_api: true
auth_api: true
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface (Not required for Ingress)
map:
  - config
  - ssl
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ssl: bool
  certfile: str
  keyfile: str
  leave_front_door_open: bool?