name: "Ingress Example"
version: "0.0.3"
slug: "nginx-ingress-example"
description: "Ingress testing"
arch:
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
map:
 - ssl
 - addons
 - backup
 - share
 - media
