name: "Zabbix Agent 6.0"
description: "Zabbix Agent 6.0"
version: "0.2.2"
slug: "zabbixagent6"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  10050/tcp: 10050
options:
  EnableRemoteCommands: 1
  server: "zabbix server"
  server_active: "zabbix server"
  hostname: "hostname"
  StartAgents: 3
  RefreshActiveChecks: 120
  BufferSend: 5
  BufferSize: 100
  Timeout: 3
  TLSConnect: "psk"
  TLSAccept: "psk"
  TLSPSKIdentity: "Identity"
  TLSPSKCode: "Preshared Key"
schema:
  EnableRemoteCommands: int
  server: str
  server_active: str
  hostname: str
  StartAgents: int
  RefreshActiveChecks: int 
  BufferSend: int 
  BufferSize: int 
  Timeout: int 
  TLSConnect: str 
  TLSAccept: str 
  TLSPSKIdentity: str 
  TLSPSKCode: str