name: "Zabbix Agent 6.0"
description: "Zabbix Agent 6.0"
version: "0.2.13"
slug: "zabbixagent6"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  10050/tcp: 10050
options:
  server: "zabbix server"
  hostname: "hostname client"
  nameserver: "name server"
schema:
  server: str
  hostname: str
  nameserver: str
