name: "Zabbix Agent 6.0"
description: "Zabbix Agent 6.0"
version: "0.2.11"
slug: "zabbixagent6"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  10050/tcp: 10050
options:
  server: "zabbix server"
  hostname: "hostname client"
schema:
  server: str
  hostname: str
