name: "Zabbix Agent 6.0"
description: "Zabbix Agent 6.0"
version: "0.1.3"
slug: "zabbixagent6"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  10050/tcp: 10050
options:
  server: "zabbix server"
  hostname: "hostname client"
  TLSConnect: "psk"
  TLSAccept: "psk"
  TLSPSKIdentity: "Identity"
  TLSPSKCode: "Private Key"
schema:
  server: str
  hostname: str
  TLSConnect: str
  TLSAccept: str
  TLSPSKIdentity: str
  TLSPSKCode: str