name: "New IDE"
description: "New IDE"
version: "0.0.18"
slug: "new_ide"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true  
url: https://github.com/GiudiciMattia/MyHomeAssistantRepo/tree/main/3-NewIDE
startup: before
ports:
  80/tcp: 80
map:
  - config:rw
  - ssl  
options:
  beer: true
  wine: true
  liquor: false
  name: "world"
  year: 2017
schema:
  beer: bool
  wine: bool
  liquor: bool
  name: str
  year: int